config/routes.rb
Rails.application.routes.draw do
  #get 'projects/index'
  #get 'projects/show'
  #get 'projects/create'
  #get 'users/show'
  #get 'users/edit'
  devise_for :users
  #get 'homes/top'
  root to: 'homes#top'
  get 'homes/about', to: 'homes#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update]
  resources :projects, only: [:new, :index, :show, :create, :destroy] do
    resources :comments, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 200 }

  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  validates :project_name, presence: true
  validates :content, presence: true, length: { maximum: 200 }

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true

  validates :introduction, length: { maximum: 100 }

  has_many :projects, dependent: :destroy
  has_many :comments, through: :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about] # top, about の2つのアクションのみログインしなくてアクセス可能にする
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user) # ログインした直後は、ユーザーの詳細ページに遷移
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @project = Project.find(params[:project_id])
  end

  def create
    @project = Project.find(params[:project_id])
    #@comment = current_user.comments.new(comment_params)
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.project_id = @project.id
    if @comment.save
      #flash[:notice] = 'You have created book successfully'
      #redirect_to book_path(@book.id)
      redirect_to project_path(@project.id)
    else
      @projects = Project.all
      @user = current_user
      render :new
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new
  end

  def index
    # @projects = Project.all
    @projects = Project.all.order(created_at: :desc)
  end

  def show
    @project = Project.find(params[:id])
    @comments = Comment.all.order(created_at: :desc)
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save
      flash[:notice] = 'You have created project successfully'
      #redirect_to book_path(@book.id)
      redirect_to project_path(@project.id)
    else
      @projects = Project.all
      @user = current_user
      render :new
    end
  end

  def destroy
    project = Project.find(params[:id])
    project.destroy
    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:project_name, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<!--Anken Comment New-->

<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container'>
    <div class='row'>
      <div class="col-sm-12 col-sm-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>コメント</h2>

        <% if @comment.errors.any? %>
          <div id="error_explanation">
          <% if @comment.errors.count == 1 %>
            <h3><%= @comment.errors.count %> error prohibited this obj from being saved:</h3>
          <% else %>
            <h3><%= @comment.errors.count %> errors prohibited this obj from being saved:</h3>
          <% end %>
            <ul>
              <% @comment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <h3><%= @project.project_name %></h3>

        <%= form_with model: @comment, url: project_comments_path, local: true do |c| %>

          <div class="form-group">
            <%= c.label "コメント" %>
            <%= c.text_area :body, autofocus: true, autocomplete: "name", class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= c.submit "コメントを返信", class: 'btn btn-secondary' %>
          </div>

         <% end %>

      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container'>
    <div class='row'>
      <h1 class="px-3 mx-auto">Welcome to
        <i class="fas fa-users"></i>
        <strong>案件募集サイト</strong>!
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>ようこそ
          <i class="fas fa-users"></i>
          <strong>案件募集サイト</strong>!!
        </h1>
        <p>In
          <i class="fas fa-users"></i>
          <strong>案件募集サイト</strong>,
        </p>
        <p>案件で人材を求めている方と</p>
        <p>案件に応募したい方を結びつけるサイトです。</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight HisTaj.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span>案件募集サイト</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li>
             <a class="nav-link text-light" href="/users/<%= current_user.id %>">
              <i class="fas fa-home"></i> Home
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/projects">
              <i class="fas fa-list"></i> 案件一覧
            </a>
          </li>
          <li>
            <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="fas fa-sign-out-alt"></i> Log out
            </a>
          </li>
          <% else %>
          <li>
            <a class="nav-link text-light" href="/">
              <i class="fas fa-home"></i> Home
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/homes/about">
              <i class="fas fa-link"></i> About
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_up">
              <i class="fas fa-user-plus"></i> Sign up
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_in">
              <i class="fas fa-sign-in-alt"></i> Log in
            </a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anken</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/index.html.erb
<!--<h1>Projects#index</h1>-->
<!--<p>Find me in app/views/projects/index.html.erb</p>-->

<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>

      <div class='col-md-3'>
        <%= link_to "新規案件登録", new_project_path, class: "btn btn-outline-secondary btn-block" %>
      </div>

      <div class='col-md-8 offset-md-1'>
        <h2>案件一覧</h2>
          <table class='table table-hover table-inverse'>
            <thead>
              <tr>
                <th>投稿日</th>
                <th>案件名</th>
                <th>詳細</th>
                <!--<th colspan="3"></th>-->
              </tr>
            </thead>
            <tbody>
              <% @projects.each do |project| %>
              <tr>
                <td>
                  <%= project.created_at %>
                </td>
                <td>
                  <%= link_to project.project_name, project_path(project.id) %>
                </td>
                <td>
                  <%= project.content %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>
</main>

app/views/projects/new.html.erb
<!-- Anken Project new.html.erb-->

<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container'>
    <div class='row'>
      <div class="col-sm-12 col-sm-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>新規案件</h2>

        <% if @project.errors.any? %>
          <div id="error_explanation">
          <% if @project.errors.count == 1 %>
            <h3><%= @project.errors.count %> error prohibited this obj from being saved:</h3>
          <% else %>
            <h3><%= @project.errors.count %> errors prohibited this obj from being saved:</h3>
          <% end %>
            <ul>
              <% @project.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= form_with model: @project, local: true do |f| %>

          <div class="form-group">
            <%= f.label "案件名" %>
            <%= f.text_field :project_name, autofocus: true, autocomplete: "name", class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label "詳細" %>
            <%= f.text_area :content, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.submit "新規登録", class: 'btn btn-secondary' %>
          </div>

        <% end %>

      </div>
    </div>
  </div>
</main>

app/views/projects/show.html.erb
<!--<h1>Projects#show</h1>-->
<!--<p>Find me in app/views/projects/show.html.erb</p>-->

<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container'>
    <div class='row justify-content-end'>
      <div class='col-4'>
        User Name: <%= current_user.name %>
        <%= link_to "コメント入力", new_project_comment_path(@project), class: "btn btn-outline-secondary btn-block" %>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-12'>
        <h2>案件詳細</h2>
        <table class='table table-striped'>
          <tr>
            <th>案件名</th>
            <th><%= @project.project_name %></th>
          </tr>
          <tr>
            <th>詳細</th>
            <th><%= @project.content %></th>
          </tr>
          <tr>
            <th>オーナー</th>
            <th><%= @project.user.name %></th>
          </tr>
          <tr>
            <th>投稿日</th>
            <th><%= @project.created_at %></th>
          </tr>
        </table>
        <br />
        <% @comments.each do |comment| %>
          <% if comment.project_id == @project.id %>
            <table class='table table-striped'>
              <tr>
                <th>ユーザー</th>
                <th><%= comment.user.name %></th>
              </tr>
              <tr>
                <th>投稿日</th>
                <th><%= comment.created_at %></th>
              </tr>
              <tr>
                <th>コメント</th>
                <th><%= comment.body %></th>
              </tr>
            </table>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/edit.html.erb
<!--<h1>Users#edit</h1>-->
<!--<p>Find me in app/views/users/edit.html.erb</p>-->

<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container'>
    <div class='row'>
      <div class="col-sm-12 col-sm-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>

        <% if @user.errors.any? %>
          <div id="error_explanation">
          <% if @user.errors.count == 1 %>
            <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
          <% else %>
            <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
          <% end %>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= form_with model: @user, local: true do |f| %>

          <div class="form-group">
            <%= f.label "Name" %>
            <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label "Introduction" %>
            <%= f.text_area :introduction, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.submit "Update User", class: 'btn btn-secondary' %>
          </div>

        <% end %>

      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<!--<h1>Anken Users#show</h1>-->
<!--<p>Find me in app/views/users/show.html.erb</p>-->

<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container'>
    <div class='row justify-content-end'>
      <div class='col-4'>
        User Name: <%= current_user.name %>
        <%= link_to("プロフィール編集", edit_user_path(current_user.id), {class: "btn btn-outline-secondary btn-block"}) %>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-12'>
        <h2>User info</h2>
        <table class='table table-striped'>
          <% if @user == current_user.id %>
          <tr>
            <th>Name</th>
            <th><%= current_user.name %></th>
          </tr>
          <tr>
            <th>Introduction</th>
            <th><%= current_user.introduction %></th>
          </tr>
          <% else %>
          <tr>
            <th>Name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>Introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <% end %>
        </table>
      <!--<div class='col-md-8 offset-md-1'>-->
        <!--<h2>Books</h2>-->

      </div>
    </div>
  </div>
</main>